import { StyleSheet, Platform } from 'react-native';
import { spacing, layout, useTheme } from '../../context/ThemeContext';

const createStyles = (colors) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: colors.background.primary,
			paddingTop: Platform.OS === 'ios' ? 50 : 0,
		},
		settingsList: {
			flex: 1,
		},
		// Card-based Design Components
		settingsCard: {
			backgroundColor: colors.background.secondary,
			borderRadius: layout.borderRadius.md,
			paddingHorizontal: spacing.md,
			paddingVertical: spacing.md,
			marginHorizontal: spacing.md,
			marginBottom: spacing.xxs,
			marginTop: spacing.lg,
			shadowColor: '#000',
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.05,
			shadowRadius: 2,
			elevation: 2,
		},
		dangerSettingsCard: {
			backgroundColor: colors.background.secondary,
			borderRadius: layout.borderRadius.md,
			paddingHorizontal: spacing.md,
			paddingVertical: spacing.md,
			marginHorizontal: spacing.md,
			marginBottom: spacing.xl,
			marginTop: spacing.md,
			borderLeftWidth: 3,
			borderLeftColor: colors.danger,
		},
		cardTitle: {
			fontSize: 18,
			fontWeight: '700',
			color: colors.text.primary,
			marginBottom: spacing.md,
			opacity: 0.8,
		},
		cardTitleCenter: {
			fontSize: 18,
			fontWeight: '700',
			textAlign: 'center',
			color: colors.text.primary,
			marginBottom: spacing.md,
			opacity: 0.8,
		},
		dangerCardTitle: {
			fontSize: 18,
			fontWeight: '700',
			textAlign: 'center',
			color: colors.danger,
			marginBottom: spacing.sm,
		},
		cardDescription: {
			fontSize: 15,
			fontWeight: '600',
			textAlign: 'center',
			color: colors.text.secondary,
			marginBottom: spacing.md,
		},
		dangerCardDescription: {
			fontSize: 15,
			fontWeight: '600',
			textAlign: 'center',
			color: colors.text.secondary,
			marginBottom: spacing.md,
		},
		// Form Components
		formGroup: {
			marginTop: spacing.xs,
			marginBottom: spacing.md,
		},
		formLabel: {
			fontSize: 16,
			fontWeight: '600',
			color: colors.text.secondary,
			marginBottom: spacing.sm,
			marginLeft: spacing.sm,
		},
		formInput: {
			backgroundColor: colors.background.primary,
			borderRadius: layout.borderRadius.sm,
			paddingHorizontal: spacing.md,
			paddingVertical: spacing.sm,
			fontSize: 16,
			color: colors.text.primary,
		},
		infoText: {
			fontSize: 16,
			color: colors.text.primary,
			backgroundColor: colors.background.primary,
			padding: spacing.sm,
			borderRadius: layout.borderRadius.sm,
			borderWidth: 1,
			borderColor: colors.border,
		},
		// Button Styles
		primaryButton: {
			backgroundColor: colors.primary,
			borderRadius: layout.borderRadius.md,
			paddingVertical: spacing.sm,
			paddingHorizontal: spacing.md,
			alignItems: 'center',
			marginTop: spacing.xs,
		},
		primaryButtonText: {
			color: colors.text.white,
			fontWeight: '600',
			fontSize: 16,
		},
		secondaryButton: {
			backgroundColor: colors.background.primary,
			borderRadius: layout.borderRadius.md,
			paddingVertical: spacing.sm,
			paddingHorizontal: spacing.md,
			alignItems: 'center',
			marginTop: spacing.xs,
			borderWidth: 1,
			borderColor: colors.border,
		},
		secondaryButtonText: {
			color: colors.text.secondary,
			fontWeight: '600',
			fontSize: 16,
		},
		dangerButton: {
			backgroundColor: colors.danger,
			borderRadius: layout.borderRadius.md,
			paddingVertical: spacing.sm,
			paddingHorizontal: spacing.md,
			alignItems: 'center',
			justifyContent: 'center',
			marginTop: spacing.xs,
			flexDirection: 'row',
		},
		dangerButtonText: {
			color: colors.background.primary,
			fontWeight: '600',
			fontSize: 16,
			marginLeft: spacing.xs,
		},
		disabledButton: {
			opacity: 0.5,
		},
		// Header Styles
		screenHeader: {
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'space-between',
			paddingHorizontal: spacing.md,
			paddingVertical: spacing.md,
		},
		headerBackButton: {
			padding: spacing.xs,
		},
		headerTitle: {
			fontSize: 20,
			fontWeight: '600',
			color: colors.text.primary,
		},
		headerRightPlaceholder: {
			width: 40,
		},
		// Setting Item Styles
		settingItem: {
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'space-between',
			paddingVertical: spacing.lg,
			borderBottomWidth: 1,
			borderBottomColor: colors.border,
		},
		settingItemLeft: {
			flexDirection: 'row',
			alignItems: 'center',
		},
		settingItemRight: {
			flexDirection: 'row',
			alignItems: 'center',
		},
		settingText: {
			fontSize: 18,
			fontWeight: '600',
			color: colors.text.primary,
			marginLeft: spacing.md,
		},
		settingSubtext: {
			fontSize: 12,
			color: colors.text.secondary,
			marginRight: spacing.xs,
			maxWidth: 150,
			textAlign: 'right',
		},
		// Profile Section Styles
		profileBackground: {
			backgroundColor: colors.background.secondary,
			marginTop: -50,
			paddingTop: 50,
		},
		profileSectionContainer: {
			paddingVertical: spacing.md,
		},
		profileSection: {
			paddingLeft: spacing.xs,
			paddingRight: spacing.xs,
			flexDirection: 'row',
			alignItems: 'center',
			width: '100%',
		},
		profileInfo: {
			marginLeft: spacing.md,
			flex: 1,
			justifyContent: 'center',
		},
		profileContent: {
			flexDirection: 'row',
			alignItems: 'center',
			paddingHorizontal: spacing.md,
			width: '100%',
			justifyContent: 'flex-start',
		},
		profileName: {
			fontSize: 18,
			fontWeight: '500',
			color: colors.text.primary,
			marginLeft: spacing.sm,
			flexShrink: 1,
			maxWidth: '80%',
			textAlign: 'center',
		},
		profileEmail: {
			color: colors.text.secondary,
		},
		avatar: {
			width: 60,
			height: 60,
			borderRadius: 30,
			overflow: 'hidden',
			justifyContent: 'center',
			alignItems: 'center',
			marginLeft: 0,
		},
		avatarImage: {
			width: '100%',
			height: '100%',
		},
		editOverlay: {
			position: 'absolute',
			bottom: -5,
			right: -5,
			backgroundColor: colors.primary,
			borderRadius: 12,
			padding: spacing.xs,
		},
		// Profile Image Styles
		profileImageSection: {
			alignItems: 'center',
			paddingVertical: spacing.md,
		},
		profileImageContainer: {
			position: 'relative',
		},
		profileImage: {
			width: 120,
			height: 120,
			borderRadius: 60,
			backgroundColor: colors.background.tertiary,
		},
		editImageButton: {
			position: 'absolute',
			right: 0,
			bottom: 0,
			backgroundColor: colors.primary,
			padding: spacing.sm,
			borderRadius: 20,
			borderWidth: 3,
			borderColor: colors.background.secondary,
		},
		defaultAvatarContainer: {
			width: 120,
			height: 120,
			justifyContent: 'center',
			alignItems: 'center',
		},
		sectionTitle: {
			fontSize: 20,
			fontWeight: '500',
			marginBottom: spacing.sm,
			color: colors.text.primary,
			opacity: 0.9,
		},
		settingSection: {
			padding: spacing.md,
			borderBottomWidth: 1,
			borderBottomColor: colors.border,
		},
		inputContainer: {
			flexDirection: 'row',
			alignItems: 'center',
			borderWidth: 1,
			borderColor: colors.border,
			borderRadius: layout.borderRadius.md,
			paddingHorizontal: spacing.md,
			marginBottom: spacing.md,
			backgroundColor: colors.background.secondary,
			height: 50,
		},
		input: {
			flex: 1,
			height: '100%',
			paddingVertical: spacing.md,
			fontSize: 16,
			color: colors.text.primary,
			textAlign: 'center',
		},
		loginButton: {
			backgroundColor: colors.primary,
			paddingVertical: spacing.md,
			paddingHorizontal: 50,
			borderRadius: layout.borderRadius.lg,
			marginTop: spacing.xs,
			marginBottom: spacing.sm,
			minWidth: 200,
			alignSelf: 'center',
		},
		loginButtonText: {
			color: colors.text.primary,
			textAlign: 'center',
			fontSize: 18,
			fontWeight: '700',
		},
		modalContainer: {
			flex: 1,
			backgroundColor: colors.background.overlay,
			justifyContent: 'center',
			padding: spacing.md,
		},
		modalContent: {
			backgroundColor: colors.background.primary,
			borderRadius: layout.borderRadius.lg,
			padding: spacing.md,
		},
		modalHeader: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			marginBottom: spacing.md,
		},
		modalTitle: {
			fontSize: 20,
			fontWeight: 'bold',
			color: colors.text.primary,
		},
		loadingOverlay: {
			position: 'absolute',
			top: 0,
			left: 0,
			right: 0,
			bottom: 0,
			backgroundColor: colors.background.overlay,
			justifyContent: 'center',
			alignItems: 'center',
		},
		safeArea: {
			flex: 1,
			backgroundColor: colors.background.primary,
		},
		logoContainer: {
			alignItems: 'center',
			marginBottom: spacing.md,
			marginTop: spacing.lg,
		},
		logo: {
			width: 250,
			height: 36,
			marginBottom: spacing.xs,
			marginTop: spacing.lg,
		},
		authContainer: {
			flex: 1,
			justifyContent: 'center',
			paddingHorizontal: spacing.md,
			backgroundColor: colors.background.primary,
		},
		formContainer: {
			width: '100%',
			maxWidth: 400,
			alignSelf: 'center',
		},
		mascotContainer: {
			alignItems: 'center',
			marginBottom: spacing.sm,
		},
		mascot: {
			width: 120,
			height: 120,
			marginBottom: spacing.md,
		},
		welcomeText: {
			fontSize: 24,
			fontWeight: '800',
			color: colors.text.primary,
			marginBottom: spacing.sm,
			textAlign: 'center',
		},
		subtitleText: {
			fontSize: 18,
			fontWeight: '700',
			color: colors.text.secondary,
			marginBottom: spacing.sm,
			textAlign: 'center',
		},
		card: {
			backgroundColor: colors.background.secondary,
			borderRadius: layout.borderRadius.md,
			padding: spacing.md,
			marginVertical: spacing.md,
			marginHorizontal: spacing.md,
			shadowColor: '#000',
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 4,
			elevation: 2,
		},
		sectionDescription: {
			fontSize: 16,
			color: colors.text.secondary,
			marginBottom: spacing.md,
		},
		settingHighlighted: {
			backgroundColor: colors.primary,
			padding: spacing.md,
			borderRadius: layout.borderRadius.sm,
			marginBottom: spacing.sm,
		},
		socialButton: {
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'center',
			backgroundColor: colors.background.primary,
			paddingVertical: spacing.md,
			paddingHorizontal: spacing.xl,
			borderRadius: layout.borderRadius.md,
			marginTop: spacing.xs,
			marginBottom: spacing.xs,
			borderWidth: 1,
			borderColor: colors.border,
			alignSelf: 'center',
		},
		socialButtonText: {
			color: colors.text.primary,
			marginLeft: spacing.sm,
			fontSize: 18,
			fontWeight: '600',
		},
		dividerContainer: {
			flexDirection: 'row',
			alignItems: 'center',
			marginVertical: spacing.md,
		},
		dividerLine: {
			flex: 1,
			height: 1,
			backgroundColor: colors.border,
		},
		dividerText: {
			color: colors.text.secondary,
			paddingHorizontal: spacing.md,
			fontSize: 16,
			fontWeight: '700',
		},
		forgotPasswordButton: {
			marginTop: spacing.sm,
			alignSelf: 'center',
		},
		forgotPasswordText: {
			color: colors.primary,
			fontSize: 16,
			fontWeight: '600',
		},
		headerContainer: {
			flexDirection: 'row',
			alignItems: 'center',
			padding: spacing.md,
			borderBottomWidth: 1,
			borderBottomColor: colors.border,
			backgroundColor: colors.background.secondary,
		},
		backButton: {
			flexDirection: 'row',
			alignItems: 'center',
			paddingVertical: spacing.sm,
		},
		headerTitle: {
			fontSize: 20,
			fontWeight: 'bold',
			color: colors.text.primary,
			marginLeft: spacing.sm,
		},
		inputGroup: {
			marginBottom: spacing.md,
		},
		label: {
			fontSize: 16,
			color: colors.text.secondary,
			marginBottom: spacing.xs,
			textAlign: 'center',
		},
		inputText: {
			fontSize: 16,
			color: colors.text.primary,
			textAlign: 'center',
		},
		saveButton: {
			backgroundColor: colors.primary,
			padding: spacing.md,
			borderRadius: layout.borderRadius.md,
			marginTop: spacing.md,
			alignItems: 'center',
		},
		saveButtonText: {
			color: colors.text.primary,
			fontSize: 16,
			fontWeight: '500',
			textAlign: 'center',
		},
		saveButtonDisabled: {
			backgroundColor: colors.primary,
			opacity: 0.5,
		},
		saveButtonTextDisabled: {
			opacity: 1,
		},
		authInputContainer: {
			flexDirection: 'row',
			alignItems: 'center',
			borderWidth: 1,
			borderColor: colors.border,
			borderRadius: layout.borderRadius.md,
			paddingHorizontal: spacing.md,
			marginBottom: spacing.md,
			backgroundColor: colors.background.secondary,
			height: 50,
			width: '100%',
		},
		authInput: {
			flex: 1,
			height: '100%',
			fontSize: 17,
			fontWeight: '600',
			color: colors.text.primary,
			paddingRight: spacing.md,
			textAlign: 'center',
		},
		segmentedControlContainer: {
			paddingHorizontal: spacing.xl,
			marginBottom: spacing.md,
		},
		segmentedControl: {
			height: 50,
		},
		segmentedControlText: {
			fontSize: 20,
			color: colors.text.primary,
		},
		segmentedControlActiveText: {
			fontSize: 20,
			color: colors.text.primary,
		},
		forgotPasswordContainer: {
			height: 40,
			justifyContent: 'center',
			marginBottom: 0,
			marginTop: -8,
		},
		settingsHeader: {
			fontSize: 19,
			fontWeight: '700',
			color: colors.text.primary,
			textAlign: 'center',
			marginTop: spacing.xs,
			marginBottom: spacing.xs,
		},
		settingsExplanation: {
			fontSize: 15,
			fontWeight: '600',
			color: colors.text.secondary,
			marginBottom: spacing.md,
			textAlign: 'center',
			marginTop: spacing.xs,
		},
		headerSettingsPages: {
			paddingLeft: spacing.xs,
			paddingRight: spacing.xs,
			flexDirection: 'row',
			alignItems: 'center',
			width: '100%',
			paddingTop: spacing.lg,
			paddingBlockEnd: spacing.xs,
			marginTop: 0,
		},
		settingRow: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			marginBottom: spacing.sm,
			paddingVertical: spacing.xs,
		},
		iconBackground: {
			width: 36,
			height: 36,
			borderRadius: 18,
			justifyContent: 'center',
			alignItems: 'center',
		},
		relationshipIntroContainer: {
			backgroundColor: colors.background.secondary,
			padding: spacing.md,
			marginTop: spacing.md,
			marginBottom: spacing.md,
			borderRadius: layout.borderRadius.md,
			marginHorizontal: spacing.md,
		},
		relationshipIntroText: {
			fontSize: 15,
			fontWeight: '600',
			fontStyle: 'italic',
			lineHeight: 20,
			color: colors.text.primary,
			opacity: 0.7,
			textAlign: 'center',
		},
		resetContainer: {
			padding: spacing.md,
			alignItems: 'center',
			marginTop: 'none',
			marginBottom: spacing.xl,
		},
		resetButton: {
			backgroundColor: '#ff7770',
			marginTop: spacing.lg,
			paddingVertical: spacing.md,
			paddingHorizontal: spacing.lg,
			borderRadius: layout.borderRadius.md,
		},
		resetButtonText: {
			color: colors.background.primary,
			fontSize: 16,
			fontWeight: '700',
		},
		sectionHeader: {
			flexDirection: 'row',
			alignItems: 'center',
			marginBottom: spacing.md,
			marginTop: spacing.lg,
		},
		iconTitleContainer: {
			flexDirection: 'row',
			alignItems: 'center',
			flex: 1,
		},
		sectionIcon: {
			marginRight: spacing.md,
		},
		notificationTitle: {
			fontSize: 24,
			fontWeight: '600',
			color: colors.primary,
		},
		helperText: {
			fontSize: 16,
			fontWeight: '600',
			lineHeight: 22,
			color: colors.text.secondary,
			paddingHorizontal: spacing.xl,
		},
		// Crd-based design
		optionCardContainer: {
			marginBottom: spacing.md,
		},
		optionCard: {
			flexDirection: 'row',
			alignItems: 'center',
			backgroundColor: colors.background.tertiary,
			borderRadius: layout.borderRadius.md,
			padding: spacing.md,
			marginVertical: spacing.xs,
		},
		optionCardActive: {
			borderWidth: 2,
			borderColor: colors.primary,
		},
		optionIcon: {
			width: 32,
			height: 32,
			alignItems: 'center',
			justifyContent: 'center',
			marginRight: spacing.md,
		},
		optionTextContainer: {
			flex: 1,
		},
		optionTitle: {
			fontSize: 16,
			fontWeight: '600',
			color: colors.text.primary,
			marginBottom: 2,
		},
		optionDescription: {
			fontSize: 14,
			color: colors.text.secondary,
		},
		// Separator styles
		separator: {
			height: 1,
			backgroundColor: colors.border,
			marginVertical: spacing.sm,
		},
		// Info banner styles
		infoBanner: {
			backgroundColor: colors.background.tertiary,
			borderRadius: layout.borderRadius.md,
			padding: spacing.md,
			marginVertical: spacing.md,
			marginHorizontal: spacing.md,
			flexDirection: 'row',
			alignItems: 'center',
		},
		infoBannerText: {
			fontSize: 14,
			color: colors.text.secondary,
			marginLeft: spacing.sm,
			flex: 1,
		},
	});

export const useStyles = () => {
	const { colors } = useTheme();
	return createStyles(colors);
};
